import { createHash } from "node:crypto";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

type SourceFile = { url: string; file: string; sha256: string; output_sha256: string; transform?: string };
const root = resolve(import.meta.dirname, "..");
const spec = JSON.parse(await readFile(resolve(root, "assets/sanotts-files.json"), "utf8")) as {
  commit: string;
  files: SourceFile[];
};
for (const entry of spec.files) {
  const response = await fetch(entry.url);
  const hasFailed = !response.ok;
  if (hasFailed) throw new Error(`${entry.url}: HTTP ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  const digest = createHash("sha256").update(bytes).digest("hex");
  const hasChanged = digest !== entry.sha256;
  if (hasChanged) throw new Error(`${entry.file}: upstream SHA-256 changed`);
  let output = bytes;
  const isVoiceLoader = entry.transform === "esm-voice";
  if (isVoiceLoader) output = Buffer.concat([bytes, Buffer.from("\nexport default SaanoVoice;\n")]);
  const isG2pLoader = entry.transform === "esm-g2p";
  if (isG2pLoader) output = Buffer.concat([bytes, Buffer.from("\nexport default SaanoG2P;\n")]);
  const isGzipAdapter = entry.transform === "gzip-magic";
  if (isGzipAdapter) {
    const source = bytes.toString();
    const marker = "async function inflate(bytes) {";
    const containsMarker = source.includes(marker);
    if (!containsMarker) throw new Error("sanoTTS Chinese gzip adapter no longer matches upstream");
    output = Buffer.from(
      source.replace(marker, `${marker}\n  if (bytes[0] !== 0x1f || bytes[1] !== 0x8b) return bytes;`),
    );
  }
  const outputHash = createHash("sha256").update(output).digest("hex");
  const hasInvalidOutput = outputHash !== entry.output_sha256;
  if (hasInvalidOutput) throw new Error(`${entry.file}: adapted SHA-256 mismatch`);
  const target = resolve(root, entry.file);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output);
}

await writeFile(
  resolve(root, "public/sanotts/SOURCE.md"),
  "# sanoTTS browser assets\n\nCopyright (C) 2026 Ampixa. Distributed under GPL-3.0-or-later; see LICENSE-GPL-3.0.txt.\nThe MIT grant in LICENSE-MIT.txt is limited to the runtime files it names; it is not applied to these web assets.\nPinyin dictionary provenance and its permissive upstream terms are in NOTICE-G2P.md.\n\nSource revision: 3de9f37cbfedb8a1edcc28f4c8139979c6fcf889 (2026-10-01).\n\nThe corresponding source, headers, language data and build scripts for these WASM binaries are available without charge at:\n\nhttps://github.com/Ampixa/sanoTTS/archive/3de9f37cbfedb8a1edcc28f4c8139979c6fcf889.tar.gz\n\nBuild instructions are in mcu/ports/wasm/README.md; build_g2p.sh and build_voices.sh generate snt_g2p and snt_voice respectively with Emscripten.\nThe Chinese front end is in web/g2p-lazy/zh/; its dictionaries are generated by tools/build_zh_g2p_web_assets.py.\n\nLocal changes from that source:\n\n- Append `export default SaanoVoice;` and `export default SaanoG2P;` to the respective JS loaders and serve as .mjs.\n- At the start of `async function inflate(bytes)` in zh_g2p.mjs, return bytes unchanged when gzip magic 1f 8b is absent. HTTP Content-Encoding may have already decompressed the response.\n- No model weights or dictionary entries were changed.\n\nThe local adapter and retrieval recipe are available at https://github.com/kexi/tokyo-od-game (scripts/fetch-sanotts.ts, assets/sanotts-files.json).\nThe retrieval script checks the SHA-256 of the unmodified source download and the resulting local file before writing.\n",
);
